package com.ilatyphi95.farmersmarket.data.entities

import com.google.firebase.Timestamp
import com.ilatyphi95.farmersmarket.utils.toDate
import com.ilatyphi95.farmersmarket.utils.toShortTime

/**
 * @param chatId unique Id generated by database when message is sent
 * @param mediaThumbUrl empty string when not specified
 * @param mediaUrl empty string when not specified
 * @param msg message content
 * @param receiverId who the message is sent to
 * @param msgType can assume value "TEXT", "IMAGE" etc.
 * @param senderId authenticated user that sent the message
 * @param timeStamp UNIX base timestamp
 */
data class ChatMessage @JvmOverloads constructor(
    val chatId: String,
    val mediaThumbUrl: String = "",
    val mediaUrl: String = "",
    val msg: String = "",
    val receiverId: String = "",
    val msgType: String = "",
    val senderId: String,
    val timeStamp: Timestamp
)